name: Deploy to EC2

on:
  push:
    branches:
      - main  # Eller den gren som du vill trigga deployen på

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 51.20.85.218 >> ~/.ssh/known_hosts  # Byt ut med din EC2 IP-adress
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}  # Refererar till den privata nyckeln som en secret

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@51.20.85.218 "cd /path/to/your/app && git pull origin main && npm install && pm2 restart app"  # Justera kommandot för din specifika deploy
